# Generated by Django 3.0.5 on 2021-06-16 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DIABOT', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='addUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=10)),
                ('lastname', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=15)),
                ('gender', models.CharField(max_length=15)),
                ('martial', models.CharField(max_length=15)),
            ],
        ),
    ]
